### ISSUE TITLE
Test video in HTML

### ISSUE THREAD

**Issue by brian-silverman** [scottsilverlabs/raspberrystem-ide#82]
We are going to want to run embedded video from the HTML projects.   Implement a test HTML page that includes the video.  Embedded video player allowing full screen is a plus.  Select a video format that runs at a reasonable resolution and frame rate, and that videos can easily be converted to.

**Comment by Slowki** [comment]
Unfortunately Chromium on the Pi is pretty much the only browser besides Lynx that doesn't support videos(HTML5 or otherwise), probably because the build is from 2011. Rumor has it there's a way to hack videos into working, but so far I haven't had any success, so I think moving to a new browser is probably the best option.
Chromium Alternatives:
* KWeb, decent performance, supports kiosk mode
* Epiphany, works pretty well, but as far as I can tell no kiosk mode
* Ice Weasel, fairly bad, but tolerable performance, needs a plugin for kiosk mode
* Webkitgtk with Python, will yield the same result as KWeb, but with slightly less overhead

KWeb or Webkitgtk is probably the best option, unless I can figure out how to get Epiphany into Kiosk mode.

**Comment by brian-silverman** [comment]
Thanks - I’m going to put this on hold for now then...  I was a little worried it might be more painful than I was hoping for.

**Comment by brian-silverman** [comment]
Shelved for now.  Other future alternative is to use a app outside of the browser - like omxplayer.
